# Generated by Django 5.1.5 on 2025-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='DEFAULT TITLE')),
                ('isbn', models.CharField(max_length=13, verbose_name='-------------')),
            ],
        ),
    ]
