# Generated by Django 5.1.5 on 2025-04-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('receiver', models.CharField(max_length=150)),
                ('body', models.CharField(default='DEFAULT', max_length=255)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='DEFAULT TITLE')),
                ('uploader', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=13, null=True, verbose_name='-------------')),
                ('description', models.CharField(max_length=512, null=True, verbose_name='DEFAULT DESCRIPTION')),
            ],
        ),
    ]
