# Generated by Django 5.1.7 on 2025-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
