# Generated by Django 5.1.5 on 2025-05-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profile_avatar'),
        ('main_app', '0005_merge_20250506_1618'),
    ]

    operations = [
    ]
