# Generated by Django 5.1.5 on 2025-05-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20250506_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='DjangoProjectFiles/avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
